name: firechat
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  cloud_firestore: ^4.15.7
  firebase_auth: ^4.17.7
  firebase_core: ^2.26.0
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  provider: ^6.1.2

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon_final.png"
  min_sdk_android: 21 # android min sdk min:16, default 21